version: "3.7"

services:
    redis:
        image: redis
        restart: always
        volumes:
            - "./data:/data"
        ports:
            - "6379:6379"

    covlog:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - "./envfile"
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - redis
